#!/bin/bash
/usr/bin/docker create -i  \
    -v "/usr:/usr" \
    -v "/lib64:/lib64" \
    -v "/etc:/etc" \
    -v "`pwd`/home:/home" \
    -v /bin:/bin \
    -v /sbin:/sbin \
    `cat build-id` /bin/bash \
   | tee create-id 

