#!/bin/sh
D=`pwd`
D=`basename $D`
echo "name=$D"
cp /etc/passwd ./
cp /etc/hadoop/conf/core-site.xml ./
docker build . \
    -t "$D" \
    | tee build.log
rm -f ./passwd
echo
cat build.log | grep built | awk '{print $3}' | tee build-id
echo


