#!/bin/bash
/usr/bin/docker run -d \
    --net=user_defined_nw --ip=192.168.1.2 \
    `cat build-id`  & > /dev/null 
    
#	-v /usr/sbin:/usr/sbin:ro \
#    -v /lib64:/lib64:ro \
#    -v /bin:/bin:ro \
#    -v /sbin:/sbin:ro \
#    `cat build-id` /bin/bash \
#   | tee create-id 

