#!/bin/bash
/usr/bin/docker create -it  \
    -u $(id -u):$(id -g) \
    -v /usr:/usr:ro \
    -v /usr/sbin:/usr/sbin:ro \
    -v /lib64:/lib64:ro \
    -v /bin:/bin:ro \
    -v /sbin:/sbin:ro \
    -v /var/run/docker.sock:/var/run/docker.sock \
    `cat build-id` /bin/bash \
   | tee create-id 

